const express=require('express');const cors=require('cors');const dotenv=require('dotenv');const{Pool}=require('pg');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const path=require('path');const fs=require('fs');
dotenv.config();const app=express();app.use(cors());app.use(express.json({limit:'1mb'}));const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:false}:false});const secret=process.env.JWT_SECRET||'development-only-change-me';
app.get('/api/health',async(req,res)=>{if(!process.env.DATABASE_URL)return res.status(503).json({ok:false,database:'not_configured'});try{await pool.query('select 1');res.json({ok:true,database:'connected'})}catch(e){res.status(503).json({ok:false,database:'disconnected'})}});
const auth=(req,res,next)=>{try{const t=(req.headers.authorization||'').replace(/^Bearer /,'');req.user=jwt.verify(t,secret);next()}catch(e){res.status(401).json({message:'Authentication required'})}};const role=r=>(req,res,next)=>r.includes(req.user.role)?next():res.status(403).json({message:'Forbidden'});
app.post('/api/auth/register',async(req,res)=>{try{const{name,email,password,role='customer'}=req.body;if(!name||!email||!password||password.length<8)return res.status(400).json({message:'Name, email and password (8+ characters) are required'});const e=email.trim().toLowerCase();if((await pool.query('select id from users where email=$1',[e])).rowCount)return res.status(409).json({message:'Email already registered'});const r=['customer','seller'].includes(role)?role:'customer';const h=await bcrypt.hash(password,12);const q=await pool.query('insert into users(name,email,password_hash,role) values($1,$2,$3,$4) returning id,name,email,role',[name.trim(),e,h,r]);const u=q.rows[0];res.status(201).json({user:u,token:jwt.sign(u,secret,{expiresIn:'7d'})})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const q=await pool.query('select id,name,email,role,password_hash from users where email=$1',[String(req.body.email||'').trim().toLowerCase()]);if(!q.rowCount||!(await bcrypt.compare(req.body.password||'',q.rows[0].password_hash)))return res.status(401).json({message:'Invalid email or password'});const{password_hash,...u}=q.rows[0];res.json({user:u,token:jwt.sign(u,secret,{expiresIn:'7d'})})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/categories',async(req,res)=>{try{res.json((await pool.query('select * from categories order by name')).rows)}catch(e){res.json([])}});
app.get('/api/products',async(req,res)=>{try{const q=String(req.query.q||'').trim();const c=req.query.category;const like='%'+q+'%';const sql=`select p.*,c.name category_name,u.name seller_name from products p left join categories c on c.id=p.category_id join users u on u.id=p.seller_id where p.is_active=true and (p.name ilike $1 or p.description ilike $1) ${c?'and c.slug=$2':''} order by p.created_at desc limit 100`;res.json((await pool.query(sql,c?[like,c]:[like])).rows)}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/addresses',auth,async(req,res)=>{try{const{full_name,phone,county,town,address_line}=req.body;const q=await pool.query('insert into addresses(user_id,full_name,phone,county,town,address_line) values($1,$2,$3,$4,$5,$6) returning *',[req.user.id,full_name,phone,county,town,address_line]);res.status(201).json(q.rows[0])}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/addresses',auth,async(req,res)=>res.json((await pool.query('select * from addresses where user_id=$1 order by created_at desc',[req.user.id])).rows));
app.post('/api/orders',auth,async(req,res)=>{const client=await pool.connect();try{await client.query('begin');const{address_id,items,payment_method='cash_on_delivery'}=req.body;if(!Array.isArray(items)||!items.length)throw Error('Cart is empty');const order=await client.query('insert into orders(user_id,address_id,status,total) values($1,$2,\'pending\',0) returning id',[req.user.id,address_id]);let total=0;for(const item of items){const p=await client.query('select id,seller_id,price,stock from products where id=$1 and is_active=true for update',[item.product_id]);if(!p.rowCount||p.rows[0].stock<Number(item.quantity))throw Error('Product unavailable or insufficient stock');const qty=Number(item.quantity),price=Number(p.rows[0].price);total+=price*qty;await client.query('update products set stock=stock-$1 where id=$2',[qty,item.product_id]);await client.query('insert into order_items(order_id,product_id,seller_id,quantity,unit_price) values($1,$2,$3,$4,$5)',[order.rows[0].id,item.product_id,p.rows[0].seller_id,qty,price])}await client.query('update orders set total=$1 where id=$2',[total,order.rows[0].id]);await client.query('insert into payments(order_id,method,status,amount) values($1,$2,\'pending\',$3)',[order.rows[0].id,payment_method,total]);await client.query('insert into order_status_history(order_id,status,changed_by,note) values($1,\'pending\',$2,\'Order placed\')',[order.rows[0].id,req.user.id]);await client.query('commit');res.status(201).json({id:order.rows[0].id,total,status:'pending'})}catch(e){await client.query('rollback').catch(()=>{});res.status(400).json({message:e.message})}finally{client.release()}});
app.get('/api/orders',auth,async(req,res)=>{const q=await pool.query(`select o.*,a.full_name,a.phone,a.county,a.town,a.address_line from orders o left join addresses a on a.id=o.address_id where o.user_id=$1 order by o.created_at desc`,[req.user.id]);res.json(q.rows)});
app.get('/api/orders/:id/tracking',auth,async(req,res)=>{const q=await pool.query('select h.* from order_status_history h join orders o on o.id=h.order_id where h.order_id=$1 and o.user_id=$2 order by h.created_at',[req.params.id,req.user.id]);res.json(q.rows)});
app.post('/api/seller/products',auth,role(['seller']),async(req,res)=>{try{const{name,description='',price,stock,category_id,image_url=''}=req.body;const q=await pool.query('insert into products(seller_id,category_id,name,description,price,stock,image_url) values($1,$2,$3,$4,$5,$6,$7) returning *',[req.user.id,category_id||null,name,description,price,stock,image_url]);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({message:e.message})}});
app.get('/api/seller/products',auth,role(['seller']),async(req,res)=>res.json((await pool.query('select * from products where seller_id=$1 order by created_at desc',[req.user.id])).rows));
app.get('/api/admin',auth,role(['admin']),async(req,res)=>{const[stats,orders]=await Promise.all([pool.query(`select count(*) orders,coalesce(sum(total),0) revenue from orders`),pool.query(`select o.*,u.name customer_name from orders o join users u on u.id=o.user_id order by o.created_at desc limit 100`)]);res.json({stats:stats.rows[0],orders:orders.rows})});

app.get('/api/seed-test-product',async(req,res)=>{try{const u=await pool.query('select id from users order by created_at limit 1');if(!u.rowCount)return res.status(400).json({message:'Register a user account on the site first, then reload this page.'});const r=await pool.query('insert into products(seller_id,name,description,price,stock,image_url) values($1,$2,$3,$4,$5,$6) returning id,name,price',[u.rows[0].id,'Test Product','A real product for testing checkout',100,20,'']);res.json({success:true,product:r.rows[0]})}catch(e){res.status(500).json({message:e.message})}});

const MPESA_BASE_URL=process.env.MPESA_ENV==='production'?'https://api.safaricom.co.ke':'https://sandbox.safaricom.co.ke';
function mpesaTimestamp(){const d=new Date();const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`}
async function getMpesaToken(){const authStr=Buffer.from(`${process.env.MPESA_CONSUMER_KEY}:${process.env.MPESA_CONSUMER_SECRET}`).toString('base64');const r=await fetch(`${MPESA_BASE_URL}/oauth/v1/generate?grant_type=client_credentials`,{headers:{Authorization:`Basic ${authStr}`}});const d=await r.json();console.log('MPESA TOKEN RESPONSE:',r.status,JSON.stringify(d));if(!r.ok)throw Error(d.errorMessage||'Could not reach M-Pesa');return d.access_token}
app.post('/api/mpesa/stkpush',auth,async(req,res)=>{try{const{order_id,phone}=req.body;console.log('STK PUSH REQUEST:',order_id,phone);if(!order_id||!phone)return res.status(400).json({message:'order_id and phone are required'});let cleanPhone=String(phone).replace(/\D/g,'');if(cleanPhone.startsWith('0'))cleanPhone='254'+cleanPhone.slice(1);else if(cleanPhone.startsWith('7')||cleanPhone.startsWith('1'))cleanPhone='254'+cleanPhone;const orderQ=await pool.query('select id,total from orders where id=$1 and user_id=$2',[order_id,req.user.id]);if(!orderQ.rowCount)return res.status(404).json({message:'Order not found'});const orderRow=orderQ.rows[0];const tok=await getMpesaToken();const ts=mpesaTimestamp();const password=Buffer.from(`${process.env.MPESA_SHORTCODE}${process.env.MPESA_PASSKEY}${ts}`).toString('base64');const payload={BusinessShortCode:process.env.MPESA_SHORTCODE,Password:password,Timestamp:ts,TransactionType:'CustomerPayBillOnline',Amount:Math.max(1,Math.round(Number(orderRow.total))),PartyA:cleanPhone,PartyB:process.env.MPESA_SHORTCODE,PhoneNumber:cleanPhone,CallBackURL:`${process.env.PUBLIC_SITE_URL}/api/mpesa/callback`,AccountReference:`JazaMart-${orderRow.id}`.slice(0,20),TransactionDesc:'JazaMart order payment'};console.log('STK PUSH PAYLOAD:',JSON.stringify(payload));const stkRes=await fetch(`${MPESA_BASE_URL}/mpesa/stkpush/v1/processrequest`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${tok}`},body:JSON.stringify(payload)});const stkData=await stkRes.json();console.log('STK PUSH RESPONSE:',stkRes.status,JSON.stringify(stkData));if(!stkRes.ok||!stkData.CheckoutRequestID)return res.status(400).json({message:stkData.errorMessage||stkData.ResponseDescription||stkData.CustomerMessage||'M-Pesa request failed'});await pool.query('update payments set checkout_request_id=$1, status=$2 where order_id=$3',[stkData.CheckoutRequestID,'pending',orderRow.id]);res.json({success:true,checkout_request_id:stkData.CheckoutRequestID})}catch(e){console.error('STK push error:',e.message);res.status(500).json({message:e.message||'M-Pesa request failed'})}});
app.post('/api/mpesa/callback',async(req,res)=>{try{console.log('MPESA CALLBACK RECEIVED:',JSON.stringify(req.body));const cb=req.body?.Body?.stkCallback;if(!cb)return res.json({ResultCode:0,ResultDesc:'Accepted'});const{CheckoutRequestID,ResultCode}=cb;if(ResultCode===0){const items=cb.CallbackMetadata?.Item||[];const receipt=items.find(i=>i.Name==='MpesaReceiptNumber')?.Value||null;await pool.query('update payments set status=$1, receipt=$2 where checkout_request_id=$3',['paid',receipt,CheckoutRequestID]);const p=await pool.query('select order_id from payments where checkout_request_id=$1',[CheckoutRequestID]);if(p.rowCount){await pool.query('update orders set status=$1 where id=$2',['paid',p.rows[0].order_id]);await pool.query('insert into order_status_history(order_id,status,changed_by,note) values($1,$2,null,$3)',[p.rows[0].order_id,'paid','M-Pesa payment received'])}}else{await pool.query('update payments set status=$1 where checkout_request_id=$2',['failed',CheckoutRequestID])}res.json({ResultCode:0,ResultDesc:'Accepted'})}catch(e){console.error('M-Pesa callback error:',e.message);res.json({ResultCode:0,ResultDesc:'Accepted'})}});
app.get('/api/orders/:id/payment-status',auth,async(req,res)=>{try{const q=await pool.query('select status from payments where order_id=$1',[req.params.id]);if(!q.rowCount)return res.json({status:'unknown'});res.json({status:q.rows[0].status})}catch(e){res.status(500).json({message:e.message})}});

if(fs.existsSync(path.join(__dirname,'..','frontend','dist'))){app.use(express.static(path.join(__dirname,'..','frontend','dist')));app.get('*',(req,res)=>req.path.startsWith('/api/')?res.status(404).json({message:'Not found'}):res.sendFile(path.join(__dirname,'..','frontend','dist','index.html')))}
async function initializeDatabase(){if(!process.env.DATABASE_URL)return;try{await pool.query('ALTER TABLE payments ADD COLUMN IF NOT EXISTS checkout_request_id text');await pool.query('ALTER TABLE payments ADD COLUMN IF NOT EXISTS receipt text');console.log('M-Pesa payment columns verified.')}catch(e){console.error('M-Pesa column migration skipped:',e.message)}if(process.env.AUTO_INIT_DB==='true'){const sql=fs.readFileSync(path.join(__dirname,'sql','schema.sql'),'utf8');await pool.query(sql);console.log('JazaMart database schema initialized/verified.')}}const port=process.env.PORT||5000;initializeDatabase().then(()=>app.listen(port,'0.0.0.0',()=>console.log(`JazaMart running on ${port}`))).catch(e=>{console.error('Database initialization failed:',e.message);process.exit(1)});
