import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');
const CONTACT={
 email:import.meta.env.VITE_CONTACT_EMAIL||'novamsawt@gmail.com',
 phone:import.meta.env.VITE_CONTACT_PHONE||'',
 whatsapp:import.meta.env.VITE_WHATSAPP_NUMBER||'254785153393',
 instagram:'https://www.instagram.com/JazaMart_Kenya/',
 facebook:'',
 x:'https://x.com/JazaMart_Kenya'
};
const whatsappUrl=CONTACT.whatsapp?`https://wa.me/${CONTACT.whatsapp.replace(/\D/g,'')}`:'';
const money=n=>`KSh ${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const token=()=>localStorage.getItem('jazamart_token');
const api=async(path,options={})=>{const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),...(token()?{Authorization:`Bearer ${token()}`}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'Request failed');return d};
const statuses=['pending','paid','processing','shipped','out_for_delivery','delivered','cancelled'];
const label=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
const fallback=[{id:'demo-1',name:'Wireless Headphones',price:2499,category_name:'Electronics',emoji:'🎧',stock:20},{id:'demo-2',name:'Smart Watch',price:3499,category_name:'Electronics',emoji:'⌚',stock:15},{id:'demo-3',name:'Running Sneakers',price:4200,category_name:'Fashion',emoji:'👟',stock:12},{id:'demo-4',name:'Backpack',price:1800,category_name:'Fashion',emoji:'🎒',stock:25}];
function App(){
 const [products,setProducts]=useState(fallback),[categoriesData,setCategoriesData]=useState([]),[query,setQuery]=useState(''),[cat,setCat]=useState('All'),[cart,setCart]=useState([]),[user,setUser]=useState(null);
 const [modal,setModal]=useState(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[orders,setOrders]=useState([]),[tracking,setTracking]=useState([]),[selectedOrder,setSelectedOrder]=useState(null),[reviews,setReviews]=useState(null),[reviewForm,setReviewForm]=useState({rating:5,comment:''});
 const [admin,setAdmin]=useState(null),[seller,setSeller]=useState(null),[customer,setCustomer]=useState(null),[form,setForm]=useState({name:'',email:'',password:'',role:'customer'}),[mode,setMode]=useState('login');
 const [addresses,setAddresses]=useState([]),[wishlist,setWishlist]=useState([]),[profile,setProfile]=useState({name:'',email:''}),[address,setAddress]=useState({full_name:'',phone:'',county:'',town:'',address_line:''}),[selectedAddress,setSelectedAddress]=useState(''),[paymentMethod,setPaymentMethod]=useState('mpesa');
 const [installPrompt,setInstallPrompt]=useState(null),[editing,setEditing]=useState(null),[productForm,setProductForm]=useState({name:'',description:'',price:'',stock:'',category_id:'',image_url:''});
 useEffect(()=>{
  const handler=e=>{e.preventDefault();setInstallPrompt(e)}; window.addEventListener('beforeinstallprompt',handler);
  if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{});
  return ()=>window.removeEventListener('beforeinstallprompt',handler);
 },[]);
 useEffect(()=>{Promise.all([fetch(`${API}/api/products`).then(r=>r.ok?r.json():fallback),fetch(`${API}/api/categories`).then(r=>r.ok?r.json():[])]).then(([p,c])=>{setProducts(p);setCategoriesData(c)}).catch(()=>{});const u=localStorage.getItem('jazamart_user');if(u&&token()){const parsed=JSON.parse(u);setUser(parsed);setProfile({name:parsed.name||'',email:parsed.email||''});if(parsed.role==='customer')openCustomer(parsed);}const c=localStorage.getItem('jazamart_cart');if(c)setCart(JSON.parse(c));},[]);
 useEffect(()=>localStorage.setItem('jazamart_cart',JSON.stringify(cart)),[cart]);
 const categories=['All',...new Set(products.map(p=>p.category_name).filter(Boolean))],filtered=useMemo(()=>products.filter(p=>(cat==='All'||p.category_name===cat)&&p.name.toLowerCase().includes(query.toLowerCase())),[products,query,cat]);
 const total=cart.reduce((s,p)=>s+Number(p.price)*p.quantity,0),count=cart.reduce((s,p)=>s+p.quantity,0);
 const flash=m=>{setMessage(m);setTimeout(()=>setMessage(''),3500)};
 function add(p){if(String(p.id).startsWith('demo-')||!p.stock)return;setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,quantity:Math.min(i.quantity+1,p.stock)}:i):[...c,{...p,quantity:1}]});setModal('cart')}
 function change(id,d){setCart(c=>c.flatMap(i=>i.id!==id?[i]:[{...i,quantity:i.quantity+d}].filter(x=>x.quantity>0)))}
 function logout(){localStorage.removeItem('jazamart_user');localStorage.removeItem('jazamart_token');setUser(null);setAdmin(null);setSeller(null);setCustomer(null);setOrders([]);setWishlist([]);flash('Logged out.');}
 async function submit(e){e.preventDefault();setLoading(true);try{const body=mode==='login'?{email:form.email,password:form.password}:{name:form.name,email:form.email,password:form.password,role:form.role};const d=await api(`/api/auth/${mode}`,{method:'POST',body:JSON.stringify(body)});localStorage.setItem('jazamart_user',JSON.stringify(d.user));localStorage.setItem('jazamart_token',d.token);setUser(d.user);setModal(null);flash(`Welcome, ${d.user.name}.`);if(d.user.role==='admin')openAdmin(d.user);else if(d.user.role==='seller')openSeller(d.user);else openCustomer(d.user);}catch(e){flash(e.message)}finally{setLoading(false)}}
 async function openCustomer(target=user){if(!target){setMode('login');setForm(f=>({...f,role:'customer'}));setModal('auth');return}if(target.role!=='customer')return flash('Customer dashboard is for customer accounts.');try{window.location.hash='customer';const d=await api('/api/customer/dashboard');setCustomer(d);setProfile({name:d.user.name||'',email:d.user.email||''});setAddresses(d.addresses||[]);setWishlist(d.wishlist||[]);setModal('customer')}catch(e){flash(e.message)}}
 async function saveProfile(){try{const d=await api('/api/me',{method:'PATCH',body:JSON.stringify(profile)});setUser(d.user);setProfile({name:d.user.name,email:d.user.email});setCustomer(c=>c?({...c,user:d.user}):c);localStorage.setItem('jazamart_user',JSON.stringify(d.user));flash('Profile updated.')}catch(e){flash(e.message)}}
 async function removeAddress(id){try{await api(`/api/addresses/${id}`,{method:'DELETE'});setAddresses(a=>a.filter(x=>x.id!==id));setCustomer(c=>c?({...c,addresses:c.addresses.filter(x=>x.id!==id)}):c);flash('Address removed.')}catch(e){flash(e.message)}}
 async function toggleWishlist(productId){try{const d=await api(`/api/wishlist/${productId}`,{method:'POST'});setWishlist(d.wishlist);setCustomer(c=>c?({...c,wishlist:d.wishlist}):c)}catch(e){flash(e.message)}}
 async function openOrders(){if(!user){setMode('login');setModal('auth');return}try{setOrders(await api('/api/orders'));setModal('orders')}catch(e){flash(e.message)}}
 async function track(o){try{setSelectedOrder(o);setTracking(await api(`/api/orders/${o.id}/tracking`));setModal('tracking')}catch(e){flash(e.message)}}
 async function loadReviews(id){try{setReviews(await api(`/api/products/${id}/reviews`));setSelectedOrder({id});setModal('reviews')}catch(e){flash(e.message)}}
 async function submitReview(e){e.preventDefault();try{await api(`/api/products/${selectedOrder.id}/reviews`,{method:'POST',body:JSON.stringify(reviewForm)});setReviewForm({rating:5,comment:''});await loadReviews(selectedOrder.id);flash('Review submitted.');}catch(e){flash(e.message)}}
 async function openCheckout(){if(!user){setMode('login');setModal('auth');return}try{const a=await api('/api/addresses');setAddresses(a);setSelectedAddress(a[0]?.id||'');setModal('checkout')}catch(e){flash(e.message)}}
 async function saveAddress(){try{const a=await api('/api/addresses',{method:'POST',body:JSON.stringify(address)});setAddresses(x=>[a,...x]);setSelectedAddress(a.id);setAddress({full_name:'',phone:'',county:'',town:'',address_line:''});flash('Address saved.')}catch(e){flash(e.message)}}
 async function placeOrder(){if(!selectedAddress)return flash('Select or save a delivery address first.');setLoading(true);try{const d=await api('/api/orders',{method:'POST',body:JSON.stringify({address_id:selectedAddress,payment_method:paymentMethod,items:cart.map(i=>({product_id:i.id,quantity:i.quantity}))})});setCart([]);setModal(null);flash(`Order ${d.order_id.slice(0,8)} created.`);await openOrders();}catch(e){flash(e.message)}finally{setLoading(false)}}
 async function openSeller(target=user){if(!target){setMode('login');setForm(f=>({...f,role:'seller'}));setModal('auth');return}if(target.role!=='seller')return flash('Only seller accounts can open the seller dashboard.');try{window.location.hash='seller';setSeller(await api('/api/seller/dashboard'));setModal('seller')}catch(e){flash(e.message)}}
 async function saveProduct(e){e.preventDefault();try{const path=editing?`/api/seller/products/${editing.id}`:'/api/seller/products';const d=await api(path,{method:editing?'PUT':'POST',body:JSON.stringify(productForm)});setSeller(s=>({...s,products:editing?s.products.map(p=>p.id===d.id?d:p):[d,...s.products]}));setEditing(null);setProductForm({name:'',description:'',price:'',stock:'',category_id:'',image_url:''});flash('Product saved.');}catch(e){flash(e.message)}}
 async function sellerStatus(id,status){try{const d=await api(`/api/seller/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});setSeller(s=>({...s,orders:s.orders.map(o=>o.id===id?{...o,status:d.status}:o)}));flash('Order status updated.')}catch(e){flash(e.message)}}
 async function openAdmin(target=user){if(!target||target.role!=='admin')return flash('Admin access required.');try{setAdmin(await api('/api/admin/dashboard'));setModal('admin')}catch(e){flash(e.message)}}
 async function adminStatus(id,status){try{await api(`/api/admin/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});setAdmin(await api('/api/admin/dashboard'));flash('Order status updated.')}catch(e){flash(e.message)}}
 async function moderateReview(id,approved){try{await api(`/api/admin/reviews/${id}`,{method:'PATCH',body:JSON.stringify({is_approved:approved})});setAdmin(await api('/api/admin/dashboard'));}catch(e){flash(e.message)}}
 async function moderateProduct(id,active){try{await api(`/api/admin/products/${id}`,{method:'PATCH',body:JSON.stringify({is_active:active})});setAdmin(await api('/api/admin/dashboard'));}catch(e){flash(e.message)}}
 return <div><header><div className="logo">Jaza<span>Mart</span></div><nav><a href="#shop">Shop</a><a href="#seller" onClick={e=>{e.preventDefault();openSeller()}}>Seller</a>{user?.role==='customer'&&<a href="#customer" onClick={e=>{e.preventDefault();openCustomer()}}>Dashboard</a>}{user&&<a href="#orders" onClick={e=>{e.preventDefault();openOrders()}}>Orders</a>}{user?.role==='admin'&&<a onClick={openAdmin}>Admin</a>}</nav><div className="actions">{installPrompt&&<button className="secondary" onClick={async()=>{const e=installPrompt;setInstallPrompt(null);await e.prompt();await e.userChoice;}}>📲 Install App</button>}{user?<>{user.role==='customer'&&<button className="user" onClick={openCustomer}>Hi, {user.name}</button>}<button className="user" onClick={logout}>Logout</button></>:<button className="login" onClick={()=>{setMode('login');setModal('auth')}}>Login / Register</button>}<button className="cart" onClick={()=>setModal('cart')}>🛒 Cart ({count})</button></div></header>
 <section className="hero"><div><p className="eyebrow">KENYA'S ONLINE MARKETPLACE</p><h1>Everything you need.<br/><span>All in one place.</span></h1><p>Shop products from trusted sellers across Kenya.</p><button onClick={()=>document.getElementById('shop').scrollIntoView({behavior:'smooth'})}>Shop Now</button></div><div className="hero-card">🛍️<strong>JazaMart</strong><small>Shop • Sell • Deliver</small></div></section>
 <main id="shop"><div className="toolbar"><h2>Popular Products</h2><input placeholder="Search products..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="categories">{categories.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="grid">{filtered.map(p=><article className="product" key={p.id}><div className="pic">{p.image_url?<img src={p.image_url} alt=""/>:(p.emoji||'📦')}</div><small>{p.category_name||'General'}</small><h3>{p.name}</h3><div className="row"><div><b>{money(p.price)}</b><small className="stock"> · {p.stock} in stock</small></div><button disabled={!p.stock||String(p.id).startsWith('demo-')} onClick={()=>add(p)}>{!p.stock?'Out of stock':String(p.id).startsWith('demo-')?'Demo':'Add to cart'}</button></div><div className="productLinks"><button className="reviewLink" onClick={()=>loadReviews(p.id)}>⭐ Reviews</button>{user?.role==='customer'&&<button className="reviewLink" onClick={()=>toggleWishlist(p.id)}>❤️ Wishlist</button>}</div></article>)}</div></main>
 <section id="seller" className="seller"><h2>Sell on JazaMart</h2><p>Manage products, orders and fulfillment from your seller dashboard.</p><button onClick={openSeller}>Open Seller Dashboard</button></section><div className="cartbar">{count?<>🛒 {count} item(s) · <b>{money(total)}</b><button onClick={()=>setModal('cart')}>View Cart</button></>:<>Your cart is empty — add a product to begin.</>}</div>
 {modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><div className={`modal ${modal==='admin'?'adminModal':modal==='customer'?'customerModal':''}`}><button className="close" onClick={()=>setModal(null)}>×</button>
 {modal==='auth'&&<form onSubmit={submit}><h2>{mode==='login'?'Welcome back':'Create your account'}</h2>{mode==='register'&&<input placeholder="Full name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input type="email" placeholder="Email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password (8+ characters)" minLength="8" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{mode==='register'&&<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="customer">Shop as Customer</option><option value="seller">Register as Seller</option></select>}<button className="primary" disabled={loading}>{loading?'Please wait…':mode==='login'?'Login':'Register'}</button><p className="switch" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Need an account? Register':'Already have an account? Login'}</p></form>}
 {modal==='cart'&&<><h2>Your Cart</h2>{cart.length?cart.map(i=><div className="cartitem" key={i.id}><b>{i.name}</b><span><button onClick={()=>change(i.id,-1)}>−</button> {i.quantity} <button onClick={()=>change(i.id,1)}>+</button></span><b>{money(i.price*i.quantity)}</b></div>):<p>Your cart is empty.</p>}<div className="carttotal">Total <b>{money(total)}</b></div><button className="primary" disabled={!cart.length} onClick={openCheckout}>Proceed to Checkout</button></>}
 {modal==='checkout'&&<><h2>Secure Checkout</h2>{addresses.length>0&&<><label>Saved delivery address</label><select value={selectedAddress} onChange={e=>setSelectedAddress(e.target.value)}><option value="">Choose</option>{addresses.map(a=><option key={a.id} value={a.id}>{a.full_name} · {a.town}, {a.county}</option>)}</select></>}<div className="addressbox"><h3>New address</h3>{['full_name','phone','county','town','address_line'].map(k=><input key={k} placeholder={{full_name:'Full name',phone:'Phone',county:'County',town:'Town',address_line:'Address / estate / building'}[k]} value={address[k]} onChange={e=>setAddress({...address,[k]:e.target.value})}/>) }<button className="secondary" onClick={saveAddress}>Save address</button></div><label>Payment</label><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}><option value="mpesa">M-Pesa</option><option value="cash_on_delivery">Cash on delivery</option></select><button className="primary" disabled={loading||!selectedAddress} onClick={placeOrder}>{loading?'Placing…':`Place Order · ${money(total)}`}</button></>}
 {modal==='orders'&&<><h2>My Orders</h2>{orders.length?orders.map(o=><div className="order" key={o.id}><div className="row"><b>#{o.id.slice(0,8)}</b><span className="status">{label(o.status)}</span><b>{money(o.total)}</b></div><small>{new Date(o.created_at).toLocaleString()}</small><div className="orderitems">{o.items.map((i,n)=><span key={n}>{i.name} × {i.quantity}</span>)}</div><button className="secondary" onClick={()=>track(o)}>Track delivery</button></div>):<p>No orders yet.</p>}</>}
 {modal==='tracking'&&<><h2>Delivery Tracking</h2><p>Order #{selectedOrder?.id?.slice(0,8)}</p><div className="timeline">{statuses.map(s=>{const hit=tracking.find(x=>x.status===s);return <div className={hit?'step done':'step'} key={s}><strong>{label(s)}</strong>{hit&&<small>{new Date(hit.created_at).toLocaleString()}</small>}</div>})}</div></>}
 {modal==='reviews'&&<><h2>Product Reviews</h2><p>⭐ {Number(reviews?.summary?.average||0).toFixed(1)} · {reviews?.summary?.count||0} review(s)</p>{user&&<form onSubmit={submitReview} className="reviewForm"><select value={reviewForm.rating} onChange={e=>setReviewForm({...reviewForm,rating:e.target.value})}>{[5,4,3,2,1].map(x=><option key={x} value={x}>{x} stars</option>)}</select><textarea placeholder="Share your experience" value={reviewForm.comment} onChange={e=>setReviewForm({...reviewForm,comment:e.target.value})}/><button className="primary">Submit Review</button></form>}{reviews?.reviews?.map(r=><div className="review" key={r.id}><b>{r.user_name} · {'⭐'.repeat(r.rating)}</b><p>{r.comment}</p></div>)}</>}
 {modal==='customer'&&customer&&<><div className="sellerHead"><div><h2>Customer Dashboard</h2><p>Welcome back, {customer.user.name}. Manage your JazaMart account.</p></div></div><div className="stats"><div><small>Orders</small><b>{customer.stats.orders}</b></div><div><small>Pending</small><b>{customer.stats.pending}</b></div><div><small>Delivered</small><b>{customer.stats.delivered}</b></div><div><small>Spent</small><b>{money(customer.stats.spent)}</b></div></div><div className="dashboardGrid"><section className="dashboardCard"><h3>👤 My Profile</h3><input value={profile.name} placeholder="Full name" onChange={e=>setProfile({...profile,name:e.target.value})}/><input value={profile.email} type="email" placeholder="Email" onChange={e=>setProfile({...profile,email:e.target.value})}/><button className="primary" onClick={saveProfile}>Save Profile</button></section><section className="dashboardCard"><h3>📦 My Orders</h3><button className="secondary" onClick={openOrders}>View all orders</button>{customer.orders.slice(0,3).map(o=><div className="miniRow" key={o.id}><span>#{o.id.slice(0,8)} · {label(o.status)}</span><b>{money(o.total)}</b></div>)}</section><section className="dashboardCard"><h3>📍 Delivery Addresses</h3>{addresses.map(a=><div className="miniRow" key={a.id}><span>{a.full_name}<small>{a.town}, {a.county}</small></span><button onClick={()=>removeAddress(a.id)}>Remove</button></div>)}<button className="secondary" onClick={()=>setModal('checkout')}>Add Address</button></section><section className="dashboardCard"><h3>🚚 Track Orders</h3>{customer.orders.slice(0,5).map(o=><div className="miniRow" key={o.id}><span>#{o.id.slice(0,8)}<small>{label(o.status)}</small></span><button onClick={()=>track(o)}>Track</button></div>)}{!customer.orders.length&&<p className="muted">No orders yet.</p>}</section><section className="dashboardCard"><h3>❤️ Wishlist</h3>{wishlist.length?wishlist.map(p=><div className="miniRow" key={p.id}><span>{p.name}<small>{money(p.price)}</small></span><button onClick={()=>toggleWishlist(p.id)}>Remove</button></div>):<p className="muted">Your wishlist is empty.</p>}</section><section className="dashboardCard"><h3>⭐ My Reviews</h3>{customer.reviews.length?customer.reviews.map(r=><div className="miniRow" key={r.id}><span>{r.product_name}<small>{'⭐'.repeat(r.rating)}</small></span></div>):<p className="muted">You have not reviewed any products yet.</p>}</section><section className="dashboardCard"><h3>⚙️ Account Settings</h3><p className="muted">Your account is protected by JazaMart authentication.</p><button className="secondary" onClick={logout}>Log out</button></section></div></>}
 {modal==='seller'&&seller&&<><div className="sellerHead"><div><h2>Seller Dashboard</h2><p>Products, sales and delivery.</p></div></div><div className="stats"><div><small>Revenue</small><b>{money(seller.stats.revenue)}</b></div><div><small>Orders</small><b>{seller.stats.orders}</b></div><div><small>Units</small><b>{seller.stats.units}</b></div><div><small>Products</small><b>{seller.products.length}</b></div></div><form className="productForm" onSubmit={saveProduct}><h3>{editing?'Edit product':'Add product'}</h3><input required placeholder="Product name" value={productForm.name} onChange={e=>setProductForm({...productForm,name:e.target.value})}/><textarea placeholder="Description" value={productForm.description} onChange={e=>setProductForm({...productForm,description:e.target.value})}/><div className="formgrid"><input required type="number" min="0" step=".01" placeholder="Price" value={productForm.price} onChange={e=>setProductForm({...productForm,price:e.target.value})}/><input required type="number" min="0" placeholder="Stock" value={productForm.stock} onChange={e=>setProductForm({...productForm,stock:e.target.value})}/></div><select value={productForm.category_id} onChange={e=>setProductForm({...productForm,category_id:e.target.value})}><option value="">Category</option>{categoriesData.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="Image URL" value={productForm.image_url} onChange={e=>setProductForm({...productForm,image_url:e.target.value})}/><button className="primary">Save Product</button></form><h3>Products</h3>{seller.products.map(p=><div className="sellerProduct" key={p.id}><span><b>{p.name}</b><small>{money(p.price)} · {p.stock} stock</small></span><button onClick={()=>{setEditing(p);setProductForm({name:p.name,description:p.description||'',price:p.price,stock:p.stock,category_id:p.category_id||'',image_url:p.image_url||''})}}>Edit</button></div>)}<h3>Incoming Orders</h3>{seller.orders.map(o=><div className="order" key={o.id}><div className="row"><b>#{o.id.slice(0,8)}</b><span>{money(o.seller_total)}</span></div><select value={o.status} onChange={e=>sellerStatus(o.id,e.target.value)}>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div>)}</>}
 {modal==='admin'&&admin&&<><h2>Admin Dashboard</h2><div className="stats"><div><small>Revenue</small><b>{money(admin.stats.revenue)}</b></div><div><small>Customers</small><b>{admin.stats.customers}</b></div><div><small>Sellers</small><b>{admin.stats.sellers}</b></div><div><small>Orders</small><b>{admin.stats.orders}</b></div></div><h3>Order Management</h3>{admin.orders.map(o=><div className="order" key={o.id}><div className="row"><b>#{o.id.slice(0,8)}</b><span>{o.customer_name}</span><b>{money(o.total)}</b></div><select value={o.status} onChange={e=>adminStatus(o.id,e.target.value)}>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div>)}<h3>Review Moderation</h3>{admin.reviews.map(r=><div className="review" key={r.id}><b>{r.product_name} · {r.user_name} · {'⭐'.repeat(r.rating)}</b><p>{r.comment}</p><button className="secondary" onClick={()=>moderateReview(r.id,!r.is_approved)}>{r.is_approved?'Hide':'Approve'}</button></div>)}<h3>Product Moderation</h3>{admin.products.map(p=><div className="sellerProduct" key={p.id}><span><b>{p.name}</b><small>{p.seller_name} · {p.is_active?'Active':'Hidden'}</small></span><button onClick={()=>moderateProduct(p.id,!p.is_active)}>{p.is_active?'Hide':'Publish'}</button></div>)}</>}
 </div></div>}
 <footer className="siteFooter"><div className="footerGrid"><div><div className="logo footerLogo">Jaza<span>Mart</span></div><p>Shop with confidence. Need help? Reach out to JazaMart through any of our contact channels.</p></div><div><h3>Contact Us</h3><div className="contactList"><a href="mailto:novamsawt@gmail.com">✉️ <b>Email</b>: novamsawt@gmail.com</a><a href={whatsappUrl} target="_blank" rel="noopener noreferrer">💬 <b>WhatsApp</b>: 0785 153 393</a></div></div><div><h3>Follow Us</h3><div className="socialList"><a href="https://www.instagram.com/JazaMart_Kenya/" target="_blank" rel="noopener noreferrer">📸 <b>Instagram</b>: JazaMart_Kenya</a><a href="https://x.com/JazaMart_Kenya" target="_blank" rel="noopener noreferrer">𝕏 <b>X</b>: JazaMart_Kenya</a><a href="https://www.tiktok.com/@kirats254" target="_blank" rel="noopener noreferrer">🎵 <b>TikTok</b>: kirats254</a></div></div></div><div className="footerBottom">© {new Date().getFullYear()} JazaMart. All rights reserved.</div></footer>
 {message&&<div className="toast">{message}</div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
Fix footer socials
